# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  aspnetcoreapp:
    image: aspnetcoreapp
    build:
      context: .
      dockerfile: aspnetcore/aspnetcoreapp/Dockerfile
    ports:
      - 5116:5116
