- name: Create new users and uid with loop
  hosts: nodes1
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create new users
      user:
        name: '{{ item.name }}'
        uid: '{{ item.uid }}'
        state: present
      loop:
        - name: Ali
          uid: 1020
        - name: Amine
          uid: 1030
        - name: Huma
          uid: 1040