- name: Install Node Exporter
  hosts: nodes
  become: true
  tasks:
   - name: Copy Node Exporter Application file
     copy:
       src: ../Applications/node_exporter-1.7.0.linux-amd64.tar.gz
       dest: /tmp/node_exporter-1.7.0.linux-amd64.tar.gz
   - name: Copy Exporter Service file
     copy:
       src: ../Applications/node_exporter.service
       dest: /etc/systemd/system/node_exporter.service
   - name: Extract Node Exporter
     command: tar xvf /tmp/node_exporter-1.7.0.linux-amd64.tar.gz -C /opt/
   - name: Extract Node Exporter
     command: mv /opt/node_exporter-1.7.0.linux-amd64 /opt/node_exporter
   - name: Create node_exporter user
     command: sudo useradd --no-create-home --shell /bin/false node_exporter 
     ignore_errors: yes
   - name: Change Source File Owner
     command: sudo chown -R node_exporter:node_exporter /opt/node_exporter
   - name: Execute Permission
     command: sudo chmod -R +x /opt/node_exporter
   - name: service always started
     systemd:
       name: node_exporter
       state: started
       enabled: yes