apiVersion: v1
kind: Pod
metadata:
 name: mypod01
spec:
 containers:
 - name: webserser01
   image: nginx:latest
   ports:
   - containerPort: 80
   resources:
   requests:
    memory: "128Mi"
    cpu: "100m" #veya 0.1 yazilabilir
   limits:
    memory: "256Mi"
    cpu: "250m" #0.25
   livenessPrope: #eger cevap geliyor basarili sayar
    httpGet:
     path: /
     port: 80
     initialDelaySeconds: 30 #30 saniye beklemenin ardindan testi baslatir
     periodSeconds: 15 # her 15 saniye tekrarlar
     timeoutSeconds: 10 # 10 saniye sonunda cevap alinmazsa timeout verir
     failureTheshold: 3 # 3 defa hatalinirsa failure verir
   readinessProbe:
    httpGet:
    path: /trafik_kabul
    port: 80
   initialDelaySeconds: 40
   


    