[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

# 1. Ham sistem güvenlik loglarını (auth.log) dinliyoruz
[INPUT]
    Name         tail
    Path         /var/log/auth.log
    Tag          linux.auth
    Parser       syslog-rfc3164

# 2. Akıllı Filtreleme: Sadece "Failed password" veya "Accepted publickey" (Başarılı/Başarısız Login) olanları tut, diğerlerini çöpe at (Maliyet ve Disk Tasarrufu)
[FILTER]
    Name         grep
    Match        linux.auth
    Regex        log .*Failed password.*|.*Accepted publickey.*|.*sudo.*

# 3. Ayıklanan temiz ve normalize edilmiş veriyi SIEM (Elasticsearch veya Graylog) portuna basıyoruz
[OUTPUT]
    Name         es
    Match        linux.auth
    Host         siem-collector.kurumsal.int
    Port         9200
    Index        corporate-security-logs
    Type         _doc
